<?php 
return array(
    'Org\WxPay\WxPayUnifiedOrder' => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayResults'      => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayNotifyReply'  => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayUnifiedOrder' => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayOrderQuery'   => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayCloseOrder'   => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayRefund'       => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayRefundQuery'  => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayDownloadBill' => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayReport'       => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayShortUrl'     => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayMicroPay'     => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayReverse'      => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayJsApiPay'     => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayAppPay'       => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',
    'Org\WxPay\WxPayBizPayUrl'    => LIB_PATH.'Org/WxPay/WxPayDataBase.class.php',

    'Common\Model\OrderStatus'    => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\RefundStatus'   => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\PayType'        => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\OrderStatus'    => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\TradeEndType'   => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\OrderType'      => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\ProjectConfig'  => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\TradeType'      => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\ActivityType'   => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\SettlementType' => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\MessageType'    => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\BalanceType'    => COMMON_PATH.'Model/StaticModel.class.php',
    'Common\Model\OrderReminderType'    => COMMON_PATH.'Model/StaticModel.class.php',
);
?>